script: bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: RewOpygGSmGLyaVANfZQ1L7Y73XNHpYc7RMgN6MWos5AOBBdbGBTjJO9RjE2tkeZCSK9q2aelM1nUQLjWjY8gDxnL7ZoeThmK0adEWgpUQIlNhlHkqpokxvhrh1ZHDlO3KX2GVFc5l9vL2pQE6Ly/PeoxpudNwUolg9Sx1jSt3LMpqLpX/IwJf0svIGF2fO4O4TPNHGKyBYSt+U42p7T5isIJHxlLS8ucxwZPJMIUDs1IhgEs6WcdD7mo9ab9ICK/V2o7ejlyZXbSYVBv4uHVq5EpHY1HQu+Uhxpb0p1djtQp7IK/5Rl0uudBqs3wWort9rFRzDn0MI3s8Tjrh3I6fYebApXISaEt8YbxTdaIshAgivXEfHJh9T6sLzQBMXgfDl0v/In9ca8dTcpm0EGbnVxDU8YVig0t2g4YMI7Q9hZdti0xKKVAo8niNWpLE6PPuCW3bT5WaXGP7lmqjFQpENrLjiJJTuoTfQiMa8b1xmnpwj0NUOM0218bHRPXPp7SnaAH5h5zWIBREc979gPH4Pw+1xVzs3yOLMjHnc+1PUy3kz9JLPiTFQeUtJNBxTNQlUy7+zu29Rh1hOGMK9/F7iKqXa0HsDaHlXi6emvWUk0Hzo7dwp1csUP9V+c57CYC78dFrgY/tOsoEKCIZyiqKhadHmUHpVU47D0i+mcmXg=
  app: stark-escarpment-25631 
